# OBJECT ORIENTED PROGRAMING

# COMMON TOPIC IN ALMOST ALL POPULAR PROGRAMING LANGUAGE(PYTHON,C++,JAVA)
# WITH COMMON IDEA BUT WITH DIFFERENT SYNTEX

# OOP IS JUST A STYLE/WAY TO WRITE A CODE

# VERY HELPFUL IN CREATING REAL WORLD PROGRAMS

# WE WILL SEE OTHER ADVANTAGES WHEN WE WILL START LEARNING OOP

# class , object(instance), method

# list class
# list object 
# method

l = [1,2,3,4]
l2 = [4,5,6,7]
l3 = ["Rohit","tanwar"]
l.append(8)